finserve:
  outputs:
    dev:
      account: WQJCOHK-WB64060
      database: FINSERVE_DB
      password: Ph5S8Ainy2iS4hG
      role: ACCOUNTADMIN
      schema: FINSERVE_DB.PUBLIC
      threads: 4
      type: snowflake
      user: muhozgu
      warehouse: FINSERVE
  target: dev
