risk:
  outputs:
    dev:
      dbname: Risk_DB
      host: postgres
      pass: ok@2026
      port: 5432
      schema: dev_schema
      threads: 4
      type: snowflake
      user: muhozgu
  target: dev
