risk:
  outputs:
    dev:
      dbname: risk_db
      host: postgres
      pass: ok@2026
      port: 5432
      schema: dev_schema
      threads: 4
      type: postgres
      user: muhozgu
  target: dev
